export const CHANGE_INPUT_VALUE   = "CHANGE_INPUT_VALUE";
export const CREATE_EMPLOYEE      = "CREATE_EMPLOYEE";
export const UPDATE_EMPLOYEE      = "UPDATE_EMPLOYEE";
export const GET_EMPLOYEE_LIST    = "GET_EMPLOYEE_LIST";
export const GET_EMPLOYEE_DETAILS = "GET_EMPLOYEE_DETAILS";
export const DELETE_EMPLOYEE      = "DELETE_EMPLOYEE";