
export const CHANGE_INPUT_VALUE = "CHANGE_EXPENSE_INPUT_VALUE";
export const SUBMIT_EXPENSE = "SUBMIT_EXPENSE";
export const GET_EXPENSE_DETAILS = "GET_EXPENSE_DETAILS";
export const GET_EXPENSES_LIST = "GET_EXPENSES_LIST";
export const UPDATE_EXPENSE = "UPDATE_EXPENSE";
export const DELETE_EXPENSE = "DELETE_EXPENSE";



// export const PRINT_EXPENSE = "PRINT_EXPENSE";
// export const CHANGE_NOMINEE_INPUT = "CHANGE_NOMINEE_INPUT";
// export const GET_PLAN_DROPDOWN = "GET_PLAN_DROPDOWN";
// export const GET_PLAN_LIST = "GET_PLAN_LIST";
// export const IS_SAME_ADDRESS_STATUS = "IS_SAME_ADDRESS_STATUS";
// export const CHECKED_IDENTITY = "CHECKED_IDENTITY";
// export const ADD_NOMINEE_FORM = "ADD_NOMINEE_FORM";
// export const REMOVE_NOMINEE_FORM = "REMOVE_NOMINEE_FORM";
// export const IS_NOMINEE_SAME_ADDRESS = "IS_NOMINEE_SAME_ADDRESS";
