
export const CHANGE_EXPENSE_FORM = "CHANGE_EXPENSE_FORM";
export const SET_EXPENSE_FORM = "SET_EXPENSE_FORM";
export const SUBMIT_EXPENSE = "SUBMIT_EXPENSE";
export const GET_EXPENSE_DETAILS = "GET_EXPENSE_DETAILS";
export const GET_EXPENSES_LIST = "GET_EXPENSES_LIST";
export const UPDATE_EXPENSE = "UPDATE_EXPENSE";
export const DELETE_EXPENSE = "DELETE_EXPENSE";
export const EXPENSE_TYPE_DROPDOWN_LIST = "EXPENSE_TYPE_DROPDOWN_LIST";