export const CHANGE_MEDICAL_TEST_INPUT = "CHANGE_MEDICAL_TEST_INPUT";
export const SUBMIT_MEDICAL_TEST = "SUBMIT_MEDICAL_TEST";
export const GET_MEDICAL_TEST_DETAILS = "GET_MEDICAL_TEST_DETAILS";
export const DELETE_MEDICAL_TEST = "DELETE_MEDICAL_TEST";
export const GET_MEDICAL_TEST_LIST = "GET_MEDICAL_TEST_LIST";
export const UPDATE_MEDICAL_TEST = "UPDATE_MEDICAL_TEST";

/**Medical */
export const GET_MEDICAL_DETAILS = "GET_MEDICAL_DETAILS";
