export const CHANGE_MEDICAL_INPUT = "CHANGE_MEDICAL_INPUT";
export const SUBMIT_MEDICAL = "SUBMIT_MEDICAL";
export const GET_MEDICAL_DETAILS = "GET_MEDICAL_DETAILS";
export const DELETE_MEDICAL = "DELETE_MEDICAL";
export const GET_MEDICAL_LIST = "GET_MEDICAL_LIST";
export const UPDATE_MEDICAL = "UPDATE_MEDICAL_TEST";
export const GET_MEDICAL_TEST_LIST_BY_AGE = "GET_MEDICAL_TEST_LIST_BY_AGE";

