export const SUBMIT_PAYMENT = "SUBMIT_PAYMENT";
export const CHANGE_INPUT_VALUE="CHANGE_INPUT_VALUE";
export const GET_PAYMENT_LIST="GET_PAYMENT_LIST";
export const SEARCH_PAYMENT_PROPOSAL="SEARCH_PAYMENT_PROPOSAL";
export const PAYMENT_STATUS="PAYMENT_STATUS";