export const CHANGE_PRODUCT_INPUT = "CHANGE_PRODUCT_INPUT";
export const EMPTY_PRODUCT_INPUT = "EMPTY_PRODUCT_INPUT";
export const SUBMIT_PRODUCT = "SUBMIT_PRODUCT";
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const GET_PRODUCT_DROPDOWN_LIST = "GET_PRODUCT_DROPDOWN_LIST";