export const CHANGE_INPUT_VALUE = "CHANGE_PROJECT_INPUT_VALUE";
export const EMPTY_PROJECT_INPUT = "EMPTY_PROJECT_INPUT";
export const SUBMIT_PROJECT = "SUBMIT_PROJECT";
export const GET_PROJECT_LIST = "GET_PROJECT_LIST";
export const GET_PROJECT_DETAILS = "GET_PROJECT_DETAILS";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const GET_PROJECT_DROPDOWN = "GET_PROJECT_DROPDOWN";
export const GET_DEFAULT_BANKS = "GET_DEFAULT_BANKS";