export const CHANGE_PROPOSALS_INPUT = "CHANGE_PROPOSALS_INPUT ";
export const GET_PLAN_LIST          = "GET_PLAN_LIST ";
export const SUBMIT_PROPOSAL        = "SUBMIT_PROPOSAL ";
export const GET_PROPOSAL_LIST      = "GET_PROPOSAL_LIST ";
export const GET_PROPOSAL_DETAILS   = "GET_PROPOSAL_DETAILS ";
export const UPDATE_PROPOSAL        = "UPDATE_PROPOSAL";
export const DELETE_PROPOSAL        = "DELETE_PROPOSAL";
