export const CHANGE_PROPOSALS_INPUT  = "CHANGE_PROPOSALS_INPUT ";
// export const ADD_SOCIAL_LINK  = "ADD_SOCIAL_LINK ";
// export const REMOVE_SOCIAL_LINK  = "REMOVE_SOCIAL_LINK ";
// export const STORE_TEAM_MEMBER  = "STORE_TEAM_MEMBER ";
// export const GET_TEAM_PROFILE_LIST  = "GET_TEAM_PROFILE_LIST ";
// export const GET_TEAM_MEMBER_DETAILS  = "GET_TEAM_MEMBER_DETAILS ";
// export const UPDATE_TEAM_MEMBER  = "UPDATE_TEAM_MEMBER ";