export const CHANGE_STAMP_STOCK_FORM = 'CHANGE_STAMP_STOCK_FORM';
export const GET_STAMP_STOCK_LIST = 'GET_STAMP_STOCK_LIST';
export const SET_STAMP_STOCK_FORM = 'SET_STAMP_STOCK_FORM';
export const GET_STAMP_STOCK_DETAILS = "GET_STAMP_STOCK_DETAILS";
export const SAVE_STAMP_STOCK_FORM = 'SAVE_STAMP_STOCK_FORM';