export const GET_UNDERWRITING_CONFIGURATIONS = "GET_UNDERWRITING_CONFIGURATIONS ";
export const SET_UNDERWRITING_CONFIGURATION_VALUE = "SET_UNDERWRITING_CONFIGURATION_VALUE ";
export const CHANGE_UNDERWRITING_INPUT = "CHANGE_UNDERWRITING_INPUT";
export const SAVE_UNDERWRITING = "SAVE_UNDERWRITING";