
import Head from "next/head";
import React, { Fragment, useState } from "react";
import Footer from "./Footer";
import Header from "./Header";
import Sidebar from "./Sidebar";

type PropsType = {
    title: string,
    children: any
  }

  /**
   * 
   * @param String title Ex: Page Title 
   * @param JSX children Ex: Render Content
   * @returns Layout
   */

const Layout = ({children, title} : PropsType) => {

  const [toggleSidebar, setToggleSidebar] = useState<boolean>(false);

  title = (typeof title !== undefined && title !== null) ? `${title} || Akij Takafful Insurance` : `Akij Takafful Insurance`;


    return (
        <Fragment>
      
        <Head>
          <title>{title}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Header/>
          {
            children
          }
          <Footer/>
        </main>
      </Fragment>
    );
};

export default Layout;